import { UserRoles } from "./enums/UserRoles";

export const testData = {
  resources: [
    "Michael Lam",
    "David Lee",
    "William Patel",
    "Jacob Ng",
    "Alexander Wong",
    "Daniel Kim",
    "Ethan Nguyen",
    "Amir Hussain",
    "Jayden Singh",
    "Liam Choi",
    "Ryan Ahmed",
    "Samantha Patel",
    "Sophia Choi",
    "Emily Patel",
    "Ava Patel",
  ],
  projectManagers: [
    "Emma Johnson",
    "Michael Smith",
    "Sophia Nguyen",
    "David Patel",
    "Olivia Lee",
    "William Kowalski",
    "Ava Hernandez",
  ],
  projectNames: [
    "Wilson",
    "Tremblay",
    "Yeung",
    "Adesanya",
    "Rossi",
    "Deol",
    "Nkrumah",
    "Guo",
    "Kaczmarek",
    "Ramirez",
    "Cheung",
    "Okafor",
    "Sidhu",
    "Adebayo",
    "Chowdhury",
    "MacDonald",
    "Abidi",
    "Stevenson",
    "Chaudhry",
    "Gervais",
    "Al-Omari",
    "Ibraheem",
    "Saleem",
    "Sutherland",
    "Haider",
    "Ngo",
    "Uddin",
    "Youssef",
    "Leung",
    "Kovacevic",
    "Grewal",
    "Adegoke",
    "Diaz",
    "Roberts",
    "Nguyen",
  ],
  users: [
    {
      firstName: "Michael",
      lastName: "Lam",
      email: "test123@test",
      password: "456",
      roles: [UserRoles.ADMIN],
      id: "123e4567-e89b-12d3-a456-426614174000",
      passwordChangedAt: new Date("2023-06-01T14:30:00Z"),
    },
  ],
};
